{% set name = "editables" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1163834902381c4613787951c5914800fdf155ae08848a373b8ea5006780977c

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - flit-core >=3.3
  run:
    - python

test:
  imports:
    - editables
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pfmoore/editables
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python library for creating 'editable wheels'
  description: A Python library for creating 'editable wheels'
  doc_url: https://pypi.org/project/editables/
  dev_url: https://github.com/pfmoore/editables

extra:
  recipe-maintainers:
    - dholth
