{% set name = "editables" %}
{% set version = "0.5" %}
{% set checksum = "309627d9b5c4adc0e668d8c6fa7bac1ba7c8c5d415c2d27f60f081f8e80d1de2" %}
{% set build = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: {{ checksum }}

build:
  number: {{ build }}
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<37]

requirements:
  host:
    - flit-core
    - pip
    - python
  run:
    - python

about:
  home: https://github.com/pfmoore/editables
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python library for creating "editable wheels"
  doc_url: https://pypi.org/project/editables/
  dev_url: https://github.com/pfmoore/editables

extra:
  recipe-maintainers:
    - dholth
